version: '3'

networks:
  rafaeldeveloper-network:

volumes:
  mysqldb:

services:
  rafaeldeveloper-redis:
    image: redis:5
    container_name: rafaeldeveloper-redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - rafaeldeveloper-network

  rafaeldeveloper-mysql:
    image: mysql
    container_name: rafaeldeveloper-mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - rafaeldeveloper-network
    volumes:
      - mysqldb:/var/lib/mysql:rw
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  rafaeldeveloper-backend:
    user: root
    build:
      context: ./base
      dockerfile: Dockerfile
    container_name: rafaeldeveloper-backend
    restart: always
    expose:
      - "8080"
    ports:
      - "9000:8080"
    depends_on:
      - rafaeldeveloper-mysql
    networks:
      - rafaeldeveloper-network
    volumes:
      - ./src/backend:/var/www/html:rw