version: '3'

networks:
  rafaeldeveloper-network:

volumes:
  mysqldb:

services:
  rafaeldeveloper-redis:
    image: redis:5
    container_name: rafaeldeveloper-redis
    expose:
      - "6379"
    ports:
      - "127.0.0.50:6379:6379"
    networks:
      - rafaeldeveloper-network

  rafaeldeveloper-mysql:
    image: mysql:5.7
    container_name: rafaeldeveloper-mysql
    expose:
      - "3306"
    ports:
      - "127.0.0.51:3306:3306"
    networks:
      - rafaeldeveloper-network
    volumes:
      - mysqldb:/var/lib/mysql:rw
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  rafaeldeveloper-base:
    user: root
    build:
      context: ./base
      dockerfile: Dockerfile
    container_name: rafaeldeveloper-base
    restart: always
    expose:
      - "8080"
    ports:
      - "127.0.0.52:80:8080"
    depends_on:
      - rafaeldeveloper-mysql
    networks:
      - rafaeldeveloper-network
    volumes:
      - ./project:/var/www/html:rw